version: 2.1
orbs:
  node: circleci/node@3.0.0
  heroku: circleci/heroku@1.2.5
workflows:
  deploy:
    jobs:
      - node/test
      - heroku/deploy-via-git:
          context:
            - hello-cicd-env
          requires:
            - node/test
          filters:
            branches:
              only: main
